### ISSUE TITLE
请问如何转为rknn模型

### ISSUE THREAD

**Issue by ywdqx** [derronqi/yolov8-face#34]

**Comment by KorolLich** [comment]
You can follow this video: https://www.youtube.com/watch?v=pN8mKZ5wpdQ
However, there are some deprecated steps so you should convert model to rknn_model_zoo's supported onnx format according to the https://github.com/airockchip/ultralytics_yolov8/blob/main/RKOPT_README.md (Because the standart ultralytics lib provides onnx model with output shape contains 3 separate tensors and at the same time ultralytics_yolov8's version provides onnx model with output shape contains 4 tensors)
Then you convert to the rknn format following the https://github.com/airockchip/rknn_model_zoo/tree/main/examples/yolov8_pose example. And now you can use the rknn inference script: https://github.com/airockchip/rknn_model_zoo/blob/main/examples/yolov8_pose/python/yolov8_pose.py
